import Head from 'next/head'
import Image from 'next/image'

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/hello?2022-09-23`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default function Home({ data }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
            CinéPoll
        </h1>

        {data.map((movie) => {
            <h2>{movie.title}</h2>

          //   <ul>
          //   {movie.showtimes.map((showtime) => {
          //     <li></li>
          //   })}
          // </ul>

        })}

      </main>

      <footer>
      </footer>
    </div>
  )
}
